'use client'

import LessonLayout, { type LessonMeta } from '@shared/components/ui/book/LessonLayout'
import { THEMES } from '@shared/components/ui/book/theme'
import {
  PageTitle, SectionTitle, BookParagraph, BookCode, BookList,
} from '@shared/components/ui/book/BookContent'

const META: LessonMeta = { subject: '人工智能程序设计', chapterTitle: 'Python基础', chapterNumber: 2, totalChapters: 8, subjectHref: '/study/ai/programming', prevChapter: { label: '开发环境配置', href: '/study/ai/programming/environment' }, nextChapter: { label: 'AI编程规范', href: '/study/ai/programming/coding-standards' }, theme: THEMES.ai }

const SPREADS = [
  { label: '基础语法', left: (<div className="space-y-4"><PageTitle>基础语法</PageTitle><SectionTitle>变量和赋值</SectionTitle><BookParagraph>Python是动态类型语言，变量不需要事先声明类型。支持多重赋值和序列解包。</BookParagraph><BookCode language="python" code={`x = 10\nname = "AI"\na, b = 1, 2  # 多重赋值\nx, y = y, x  # 交换变量`} /><SectionTitle>字符串操作</SectionTitle><BookParagraph>Python提供丰富的字符串处理功能，包括切片、格式化、模板字符串等。</BookParagraph><BookCode language="python" code={`s = "Hello AI"\nprint(s[0:5])  # 切片\nprint(f"value: {x}")  # f-string`} /></div>), right: (<div className="space-y-4"><SectionTitle>列表推导式</SectionTitle><BookParagraph>列表推导式是Python特有的语法糖，可以用简洁的方式创建列表。</BookParagraph><BookCode language="python" code={`squares = [x**2 for x in range(10)]\nevens = [x for x in range(20) if x % 2 == 0]\nmatrix = [[i+j for j in range(3)] for i in range(3)]`} /></div>) },
  { label: '数据类型', left: (<div className="space-y-4"><PageTitle>数据类型</PageTitle><SectionTitle>列表和元组</SectionTitle><BookParagraph>列表是可变的序列，元组是不可变的序列。两者都支持索引、切片和迭代。</BookParagraph><BookCode language="python" code={`lst = [1, 2, 3]\nlst.append(4)\ntup = (1, 2, 3)`} /><SectionTitle>字典和集合</SectionTitle><BookParagraph>字典存储键值对，集合存储唯一元素。两者都使用哈希表实现，查找效率O(1)。</BookParagraph></div>), right: (<div className="space-y-4"><SectionTitle>NumPy数组</SectionTitle><BookParagraph>NumPy是AI编程的核心库，提供高性能的多维数组对象和数学函数。</BookParagraph><BookCode language="python" code={`import numpy as np\narr = np.array([[1,2,3],[4,5,6]])\nprint(arr.shape, arr.dtype)\nprint(arr @ arr.T)  # 矩阵乘法`} /></div>) },
  { label: '控制流程', left: (<div className="space-y-4"><PageTitle>控制流程</PageTitle><SectionTitle>条件判断</SectionTitle><BookCode language="python" code={`if x > 0:\n    print("positive")\nelif x == 0:\n    print("zero")\nelse:\n    print("negative")`} /><SectionTitle>循环</SectionTitle><BookCode language="python" code={`for i in range(10):\n    print(i)\n\nwhile x > 0:\n    x -= 1`} /></div>), right: (<div className="space-y-4"><SectionTitle>异常处理</SectionTitle><BookParagraph>使用try/except捕获和处理异常，确保程序健壮性。</BookParagraph><BookCode language="python" code={`try:\n    result = risky_operation()\nexcept ValueError as e:\n    print(f"Error: {e}")\nfinally:\n    cleanup()`} /></div>) },
  { label: '函数编程', left: (<div className="space-y-4"><PageTitle>函数编程</PageTitle><SectionTitle>函数定义</SectionTitle><BookParagraph>Python支持位置参数、默认参数、关键字参数和可变参数。</BookParagraph><BookCode language="python" code={`def train(model, data, lr=0.01, epochs=10, **kwargs):\n    for epoch in range(epochs):\n        loss = model.fit(data)\n        print(f"Epoch {epoch}, loss={loss}")`} /></div>), right: (<div className="space-y-4"><SectionTitle>高阶函数</SectionTitle><BookParagraph>函数是一等公民，可以作为参数传递或返回值。</BookParagraph><BookCode language="python" code={`list(map(lambda x: x*2, [1,2,3]))\nlist(filter(lambda x: x>0, [-1,0,1,2]))\nfrom functools import reduce\nreduce(lambda a,b: a+b, [1,2,3,4])`} /></div>) },
  { label: '面向对象', left: (<div className="space-y-4"><PageTitle>面向对象</PageTitle><SectionTitle>类和对象</SectionTitle><BookParagraph>Python的面向对象编程支持继承、多态、封装等特性。</BookParagraph><BookCode language="python" code={`class Model:\n    def __init__(self, name):\n        self.name = name\n    def train(self, data):\n        raise NotImplementedError\n\nclass NeuralNet(Model):\n    def train(self, data):\n        print(f"Training {self.name}")`} /></div>), right: (<div className="space-y-4"><SectionTitle>装饰器</SectionTitle><BookParagraph>装饰器可以在不修改函数代码的情况下增加功能，常用于日志、计时等。</BookParagraph><BookCode language="python" code={`import time\ndef timer(func):\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        print(f"Time: {time.time()-start:.2f}s")\n        return result\n    return wrapper\n\n@timer\ndef train_model(): pass`} /></div>) },
  { label: '模块与包', left: (<div className="space-y-4"><PageTitle>模块与包</PageTitle><SectionTitle>模块导入</SectionTitle><BookParagraph>使用import语句导入模块，支持绝对导入和相对导入。</BookParagraph><BookCode language="python" code={`import numpy as np\nfrom sklearn.linear_model import LinearRegression\nfrom .utils import preprocessing`} /><SectionTitle>包结构</SectionTitle><BookParagraph>包是包含__init__.py文件的目录，用于组织相关模块。</BookParagraph></div>), right: (<div className="space-y-4"><SectionTitle>常用标准库</SectionTitle><BookList items={['os/sys：系统和文件操作','json/csv：数据格式处理','re：正则表达式','collections：高级数据结构','multiprocessing：并行计算']} /></div>) },
]

export default function ProgrammingPythonPage() { return <LessonLayout meta={META} spreads={SPREADS} /> }
